CREATE DATABASE  Aruba

CREATE TABLE [dbo].[User]
(
    Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Surname NVARCHAR(255) NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    FiscalCode NVARCHAR(255) NOT NULL,
    Birthday DATE NOT NULL
);

CREATE TABLE [dbo].[Practice]
(
    Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    UserId BIGINT NOT NULL FOREIGN KEY REFERENCES [User](Id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    State INT NOT NULL,
    Attachment NVARCHAR(255)
);

CREATE TABLE [dbo].[History]
(
    Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PracticeId BIGINT NOT NULL FOREIGN KEY REFERENCES [Practice](Id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    State INT NOT NULL,
    Timestamp DATETIME
);